# 配置MySQL数据连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/repair?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
#  mail:
#    host: smtp.163.com
#    username: maxinhangdoit@163.com
#    password: PLLIICTXALTYPEKI
#    port: 25
#    default-encoding: UTF-8
#    test-connection: true
# 服务端口
server:
  port: 8888
#  servlet:
#    context-path: /repair


# mybatis xml
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xpu.repair.pojo.entity
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启自动驼峰转换
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

# 邮件配置

